apiVersion: virtualization.k8c.io/v1alpha1
kind: KubeVCluster
networkConfiguration:
  dnsServerIP: "8.8.8.8"
  networkCIDR: "10.156.0.0/16"
  serviceCIDR: "10.157.0.0/16"
  gatewayIP: "10.156.0.1"
controlPlane:
  hosts:
    - address: "34.179.224.188"
      sshUsername: "root"
      sshPrivateKeyFile: "/training/.secrets/ssh-private-key"
staticWorkers:
  hosts:
    - address: "34.179.222.182"
      sshUsername: "root"
      sshPrivateKeyFile: "/training/.secrets/ssh-private-key"
loadBalancer:
  metallb:
    # TODO ext ips from gce
    ipRange: "192.168.99.100-192.168.99.104"
storage:
  longhorn: {}
