apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-vm
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        vm: my-vm
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        # TODO explain
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: root-volume
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              <FILL-IN-CLOUD-CONFIG>
      networks:
        - name: default
          pod: {}
  dataVolumeTemplates:
    - metadata:
        name: root-volume
      spec:
        source:
          pvc:
            namespace: default
            name: ubuntu-image
        pvc:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          storageClassName: longhorn
          resources:
            requests:
              storage: 10Gi
