apiVersion: v1
kind: Service
metadata:
  name: my-vm-ssh
  annotations:
    metallb.io/address-pool: ippool-kubev
spec:
  type: LoadBalancer
  selector:
    vm: my-vm
  ports:
    - port: 22
      targetPort: 22
      nodePort: 30022
