apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-image
  namespace: default
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-serve\
        r-cloudimg-amd64.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    storageClassName: longhorn
    resources:
      requests:
        storage: 10Gi
